### ISSUE TITLE
Small sample dataset

### ISSUE THREAD

**Issue by willmoffat** [rictic/reconciliation_ui#1]
The sample data is 1000 items long. When I was demoing the loader, I found that 15 items was enough to prove the point. Could we add another, small, dataset?

**Comment by rictic** [comment]
That's a really good point.  I've been trimming them when I've been testing almost without thinking.  The datasets were from back when we were testing the speed of the service (and it was under much less load).  I'll trim both of them down.

**Comment by rictic** [comment]
Done: 1c56218484f5626e85c5fbd2f549f154bc3c7400

**Comment by willmoffat** [comment]
much better, thanks!
